import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import {
    faArrowDown,
    faArrowUp,
    faArrowsAlt,
    faArrowsAltV,
    faArrowAltCircleDown,
    faAngleDoubleRight,
    faBackspace,
    faCaretDown,
    faClipboard,
    faClipboardList,
    faSearch,
    faFilter,
    faArrowLeft,
    faExclamation,
    faPaperPlane,
    faCheckCircle,
    faTimes,
    faEllipsisV,
    faEllipsisH,
    faMinus,
    faShare,
    faCog,
    faPaperclip,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faTrashAlt,
    faPen,
    faSpinner,
    faUpload,
    faPlus,
    faUndo,
    faCommentAlt,
    faInbox,
    faArchive,
    faUserFriends,
    faUser,
    faUsers,
    faBullhorn,
    faHistory,
    faFileAlt,
    faLink,
    faLevelUpAlt,
    faChalkboardTeacher,
    faClipboardCheck,
    faStar,
    faEdit,
    faCopy,
    faUndoAlt,
    faClock,
    faExclamationCircle,
    faQuestion,
    faQuestionCircle,
    faCheck,
    faHeart,
    faUserEdit,
    faBars,
} from '@fortawesome/free-solid-svg-icons'

import {
    faCheckCircle as farCheckCircle,
    faEye as farEye,
    faCheckCircle as fasCheckCircle,
    faTimesCircle as fasTimesCircle,
    faPaperPlane as fasPaperPlane,
    faCommentAlt as fasCommentAlt,
    faClipboard as farClipboard,
    faCheckSquare as farCheckSquare,
    faStar as farStar,
    faEdit as farEdit,
    faClock as farClock,
    faHeart as farHeart
} from '@fortawesome/free-regular-svg-icons'

export default () => library.add(
    fab,
    faArrowDown,
    faArrowUp,
    faArrowsAlt,
    faArrowsAltV,
    faArrowAltCircleDown,
    faAngleDoubleRight,
    faBackspace,
    faCaretDown,
    faClipboard,
    farClipboard,
    faClipboardList,
    faSearch,
    faFilter,
    faArrowLeft,
    faExclamation,
    faPaperPlane,
    faCheckCircle,
    farCheckCircle,
    faTimes,
    faEllipsisV,
    faEllipsisH,
    faMinus,
    farEye,
    faShare,
    fasCheckCircle,
    fasTimesCircle,
    faCog,
    faPaperclip,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faPen,
    faTrashAlt,
    faSpinner,
    faUpload,
    faPlus,
    faUndo,
    faCommentAlt,
    faInbox,
    fasPaperPlane,
    faArchive,
    faUserFriends,
    faUser,
    faUsers,
    faBullhorn,
    faHistory,
    faFileAlt,
    fasCommentAlt,
    faLink,
    faLevelUpAlt,
    farCheckSquare,
    faChalkboardTeacher,
    faClipboardCheck,
    faStar,
    farStar,
    faEdit,
    farEdit,
    faCopy,
    faUndoAlt,
    faClock,
    farClock,
    faQuestion,
    faQuestionCircle,
    faExclamationCircle,
    faCheck,
    faHeart,
    farHeart,
    faUserEdit,
    faBars,
)